# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170417_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extractPath',
            field=models.TextField(default='null'),
        ),
    ]
